services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: challenge_n8n
    env_file: ../.env
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=${MY_NGROK_URL}
      - GENERIC_TIMEZONE=America/Santiago
      - TZ=America/Santiago
    volumes:
      - n8n_storage:/home/node/.local/share/n8n
      - ../backend-n8n/documentos:/files

volumes:
  n8n_storage:
